# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A test function
#' @description A test function
#' @param x a number
#' @export
timesTwo <- function(x) {
    .Call('_StatComp21092_timesTwo', PACKAGE = 'StatComp21092', x)
}

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param thin the number of between-sample random numbers
#' @return random sample list
#' @export
gibbsC <- function(N, thin) {
    .Call('_StatComp21092_gibbsC', PACKAGE = 'StatComp21092', N, thin)
}

