# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param x the number of samples
#' @export
timesTwo <- function(x) {
    .Call('_StatComp21092_timesTwo', PACKAGE = 'StatComp21092', x)
}

